### ISSUE TITLE
Wordpress blocking legit users

### ISSUE THREAD

**Issue by dschoerk** [D43Gaming/d43-issuetracker#1]
![grafik](https://user-images.githubusercontent.com/913265/34836817-51de026c-f6f9-11e7-9054-cd0b6b94b4fb.png)

**Comment by Koalatyyy** [comment]
Enabled Stop Spammers plugin to work on Wordpress forms only 
If we get loads of spam feel free to re-enable it. Lets see if it helps.

**Comment by dschoerk** [comment]
increased "Check for Many Hits in a Short Time"
