### ISSUE TITLE
CJ maps

### ISSUE THREAD

**Issue by dschoerk** [D43Gaming/d43-issuetracker#4]
set sv_maprotation "gametype cj map mp_galaxy gametype cj map mp_balance gametype cj map mp_bouncer_training gametype cj map mp_canyon gametype cj map mp_cheops gametype cj map mp_codjumper_training gametype cj map mp_crazy_jump gametype cj map mp_digital gametype cj map mp_dungeon_p gametype cj map mp_easy_jump gametype cj map mp_empire gametype cj map mp_fly gametype cj map mp_ib_glass_v3 gametype cj map mp_minecraft gametype cj map mp_peds_propel gametype cj map mp_strafe_jumps gametype cj map mp_sunset gametype cj map mp_the_extreme gametype cj map mp_vectra gametype cj map mp_to_the_moon gametype cj map mp_palm gametype cj map mp_palm_v2 gametype cj map mp_descent_v2 gametype cj map mp_lawless_v3 gametype cj map mp_4_seasons  gametype cj map mp_descent_v3 gametype cj map mp_newgate gametype cj map mp_il_jump gametype cj map mp_mystic gametype cj map mp_mystic_v3 gametype cj map mp_dark gametype cj map mp_dark_v3 gametype cj map mp_race"
[6:39 PM] 🖖 Mimimimi: to the moon was nice too
[6:39 PM] 🖖 Mimimimi: until the crouch jumping i think xD
[6:40 PM] ARtemachka: xD
[6:40 PM] ARtemachka: well sunset is nice too
[6:40 PM] ARtemachka: before the broken bounce
[6:40 PM] ARtemachka: xD
[6:42 PM] ARtemachka: so u could just remove next ones from the list: sunset, the_extreme,dark, dark_v3
[6:43 PM] ARtemachka: they are the most difficult (saying about ez way)

**Comment by Koalatyyy** [comment]
Can look at adding these this weekend.

**Comment by Koalatyyy** [comment]
Imke may want to suggest some maps too.

**Comment by Koalatyyy** [comment]
Done.
